version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
      - mkdir test-reports
  build:
    commands:
    - pytest
      --html=test-reports/report.html
      --self-contained-html
      -s
      -v
      --cov=dspt
      --cov-report=html:test-reports/coverage
      --junitxml=test-reports/junit.xml
      --log-file=test-reports/logs.txt
      tests
reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml