version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
      - mkdir test-reports
      - printenv
  build:
    commands:
    - python -m pytest --junitxml=test-reports/junit.xml tests

reports:
  report:
    files:
      - 'junit.xml'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml

artifacts:
  files:
    - '**/**'
